server:
  port: 80


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://sh-cynosdbmysql-grp-4n86zp2q.sql.tencentcdb.com:20907/relia
#    url: jdbc:mysql://localhost/test
    username: root
    password: Relia123456
  mvc:
    view:
      suffix: .html
      prefix: /

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
